### ISSUE TITLE
tiles should span on the full width

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/c6h6-homepage#4]
@Sebastien-Ahkrin 

The goal in this project is that when we click on a tab the tiles span on the full width of the page and not only in the column. We have too many tiles and this is why we need those tabs. Showing them in only one column does not help.

Could you easily change this ?

![image](https://user-images.githubusercontent.com/1484241/87555486-d00b4080-c6b5-11ea-9d95-741584d3d595.png)

**Comment by Sebastien-Ahkrin** [comment]
ok :) i will do that, you can assign this issue to me ! @lpatiny
